[package]
name = "counter"
version = "0.1.0"
description = "Counter"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "counter"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.27.0"
num-traits = "0.2"
num-derive = "0.3"