[programs.localnet]
counter = "CcXBZXzEMqrNfHx7CrLVEefiGrVrkZZxMgAr1DRaRsFz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/.bin/mocha -t 1000000 -r ts-node/register tests/*.spec.ts"
